# Problem 1

In [ ]:
# 1 - numpy kütüphanesini import edin

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin

# 3 - matris'in boyutunu öğrenin

# 4 - matris'i yeniden boyutlandırın

# 5 - matris'in boyut sayısını öğrenin



In [17]:
import numpy as np
m = np.array([1,4,7,9,3,6])
print(m.shape)

n = m.reshape(3,2)
print(n)

print(n.shape)



(6,)
[[1 4]
 [7 9]
 [3 6]]
(3, 2)


# Problem 2

In [ ]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin

# 2 - Oluşturduğunuz matrisi parçalayın

# 3 - Parçalanmış matrisleri birleştirin


In [23]:
a = np.array([1,3,5,7,9])
b = np.split(a,[2,4])
print(b)
print(np.concatenate(b))

[array([1, 3]), array([5, 7]), array([9])]
[1 3 5 7 9]


# Problem 3

In [14]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin

# 2 - matris'in özelliklerini inceleyin

sayılar = np.arange(5, 101, 2)
random_sayılar = np.random.choice(sayılar,10)
matris = np.reshape(random_sayılar, (5,2))
print(matris)
print(matris[3:])
print(matris > 70)
print(matris * 9)
print(np.subtract(matris,3))



[[ 9 27]
 [39  7]
 [49 69]
 [45 79]
 [87 51]]
[[45 79]
 [87 51]]
[[False False]
 [False False]
 [False False]
 [False  True]
 [ True False]]
[[ 81 243]
 [351  63]
 [441 621]
 [405 711]
 [783 459]]
[[ 6 24]
 [36  4]
 [46 66]
 [42 76]
 [84 48]]
