# Problem 1 

In [1]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
array = np.array([65,87,24,9,76])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
print(np.sort(array))


[ 9 24 65 76 87]


# Problem 2

In [27]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
sayilar = np.array([10,15,30,45,60])
print(sayilar)


# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
sayilar2= np.arange(5,15)
print(sayilar2)

 
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
sayilar3= np.arange(50,100,5)
print(sayilar3)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
sayilar4= np.zeros(10)
print(sayilar4)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
sayilar5= np.ones(10)
print(sayilar5)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
sayilar6= np.linspace(0,100,5)
print(sayilar6)


# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
random_numbers=np.random.randint(10,31,size=5)
print(random_numbers)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.

random_numbers2= np.random.uniform(-1,1, size=10)
print(random_numbers2)
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
random_numbers3= np.random.randint(10,50, size= (3,5))
print(random_numbers3)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print(random_numbers3.sum(axis=0))
print(random_numbers3.sum(axis=1))   

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(random_numbers3.max())
print(random_numbers3.min())
print(random_numbers3.mean())
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print(random_numbers3.argmax())

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
random_numbers4 = np.random.randint(10,20, size=8)
print(random_numbers4[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(random_numbers4[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(random_numbers3[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(random_numbers3[1,2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(random_numbers3[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(random_numbers3**2)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
random_numbers5 = np.random.randint(-50,50, size= (3,5))
print(random_numbers5)
print(random_numbers5>0) and (random_numbers5 %2==0)

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[27 28 19 30 16]
[-0.71503314  0.95841719 -0.21664514  0.48603253  0.63937814 -0.49636031
 -0.75349403 -0.98386798  0.75557899  0.74894376]
[[17 35 28 17 22]
 [29 31 37 48 49]
 [27 31 40 12 35]]
[ 73  97 105  77 106]
[119 194 145]
49
12
30.533333333333335
9
[11 11 11]
[10 19 18 14 16 11 11 11]
[17 35 28 17 22]
37
[17 29 27]
[[ 289 1225  784  289  484]
 [ 841  961 1369 2304 2401]
 [ 729  961 1600  144 1225]]
[[ 21 -49  40 -36 -20]
 [-18 -38 -16  20  27]
 [ 39 -10  25  31  16]]
[[ True False  True False False]
 [False False False  True  True]
 [ True False  True  True  True]]
